
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    # 微信登录接口代理
    location /api/weixin {
        proxy_pass https://open.weixin.qq.com;
        proxy_set_header Host open.weixin.qq.com;
        proxy_set_header User-Agent "Mozilla/5.0 (Linux; Android 7.0; Mi-4c Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043632 Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/WIFI Language/zh_CN";
        proxy_set_header Referer "https://open.weixin.qq.com/";
        proxy_ssl_server_name on;
    }

    # 微信扫码状态轮询代理
    location /api/weixin-long {
        proxy_pass https://long.open.weixin.qq.com;
        proxy_set_header Host long.open.weixin.qq.com;
        proxy_set_header User-Agent "Mozilla/5.0 (Linux; Android 7.0; Mi-4c Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043632 Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/WIFI Language/zh_CN";
        proxy_set_header Referer "https://open.weixin.qq.com/";
        proxy_ssl_server_name on;
    }

    # Hortor登录接口代理
    location /api/hortor {
        proxy_pass https://comb-platform.hortorgames.com;
        proxy_set_header Host comb-platform.hortorgames.com;
        proxy_set_header User-Agent "Mozilla/5.0 (Linux; Android 12; 23117RK66C Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.74 Mobile Safari/537.36";
        proxy_set_header Origin "https://open.weixin.qq.com";
        proxy_set_header Referer "https://open.weixin.qq.com/";
        proxy_set_header Content-Type "text/plain; charset=utf-8";
        proxy_ssl_server_name on;
    }

    location / {
        root   /app/web;
        try_files $uri $uri/ /index.html;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root    /app/web;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}

